[[main]]
  name = "Home"
  url = "/"
  weight = 5

[[main]]
  name = "Résumé"
  url = "/resume/"
  weight = 10

[[main]]
  name = "Projects Blog"
  url = "https://derek.engineer"
  weight = 20
  [main.params]
    target = "_blank"
